/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/funding` | `/funding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/kyc-details` | `/kyc-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/kyc-intro` | `/kyc-intro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(vc)'}/apply` | `/apply`; params?: Router.UnknownInputParams; } | { pathname: `/deal/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/invest/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/funding` | `/funding`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/kyc-details` | `/kyc-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/kyc-intro` | `/kyc-intro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/terms` | `/terms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(vc)'}/apply` | `/apply`; params?: Router.UnknownOutputParams; } | { pathname: `/deal/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/invest/[slug]`, params: Router.UnknownOutputParams & { slug: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/funding${`?${string}` | `#${string}` | ''}` | `/funding${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/kyc-details${`?${string}` | `#${string}` | ''}` | `/kyc-details${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/kyc-intro${`?${string}` | `#${string}` | ''}` | `/kyc-intro${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/terms${`?${string}` | `#${string}` | ''}` | `/terms${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/portfolio${`?${string}` | `#${string}` | ''}` | `/portfolio${`?${string}` | `#${string}` | ''}` | `${'/(vc)'}/apply${`?${string}` | `#${string}` | ''}` | `/apply${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/funding` | `/funding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/kyc-details` | `/kyc-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/kyc-intro` | `/kyc-intro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(vc)'}/apply` | `/apply`; params?: Router.UnknownInputParams; } | `/deal/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/invest/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/deal/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/invest/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
    }
  }
}
