export type {
  KycStatus,
  FundingSourceType,
  FundingSourceStatus,
  CampaignStatus,
  InvestmentStatus,
  ApplicationStatus,
  VCApplicationStatus,
  User,
  FundingSource,
  Campaign,
  InvestmentIntent,
  FounderApplication,
  EventLog,
  Database,
  VCInfo,
  VCApplication,
  VCDeal,
  OnboardingStep,
} from '@/lib/shared/types';
